//// Automatically Generated From SyntaxNodes.swift.gyb.
//// Do Not Edit Directly!
//===--- SyntaxEnum.swift - Enum for exhaustive Syntax node switching -----===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2022 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

/// Enum to exhaustively switch over all different syntax nodes.
public enum SyntaxEnum {
  case unknown(UnknownSyntax)
  case token(TokenSyntax)
  case decl(DeclSyntax)
  case expr(ExprSyntax)
  case stmt(StmtSyntax)
  case type(TypeSyntax)
  case pattern(PatternSyntax)
  case unknownDecl(UnknownDeclSyntax)
  case unknownExpr(UnknownExprSyntax)
  case unknownStmt(UnknownStmtSyntax)
  case unknownType(UnknownTypeSyntax)
  case unknownPattern(UnknownPatternSyntax)
  case codeBlockItem(CodeBlockItemSyntax)
  case codeBlockItemList(CodeBlockItemListSyntax)
  case codeBlock(CodeBlockSyntax)
  case inOutExpr(InOutExprSyntax)
  case poundColumnExpr(PoundColumnExprSyntax)
  case tupleExprElementList(TupleExprElementListSyntax)
  case arrayElementList(ArrayElementListSyntax)
  case dictionaryElementList(DictionaryElementListSyntax)
  case stringLiteralSegments(StringLiteralSegmentsSyntax)
  case tryExpr(TryExprSyntax)
  case awaitExpr(AwaitExprSyntax)
  case declNameArgument(DeclNameArgumentSyntax)
  case declNameArgumentList(DeclNameArgumentListSyntax)
  case declNameArguments(DeclNameArgumentsSyntax)
  case identifierExpr(IdentifierExprSyntax)
  case superRefExpr(SuperRefExprSyntax)
  case nilLiteralExpr(NilLiteralExprSyntax)
  case discardAssignmentExpr(DiscardAssignmentExprSyntax)
  case assignmentExpr(AssignmentExprSyntax)
  case sequenceExpr(SequenceExprSyntax)
  case exprList(ExprListSyntax)
  case poundLineExpr(PoundLineExprSyntax)
  case poundFileExpr(PoundFileExprSyntax)
  case poundFileIDExpr(PoundFileIDExprSyntax)
  case poundFilePathExpr(PoundFilePathExprSyntax)
  case poundFunctionExpr(PoundFunctionExprSyntax)
  case poundDsohandleExpr(PoundDsohandleExprSyntax)
  case symbolicReferenceExpr(SymbolicReferenceExprSyntax)
  case prefixOperatorExpr(PrefixOperatorExprSyntax)
  case binaryOperatorExpr(BinaryOperatorExprSyntax)
  case arrowExpr(ArrowExprSyntax)
  case floatLiteralExpr(FloatLiteralExprSyntax)
  case tupleExpr(TupleExprSyntax)
  case arrayExpr(ArrayExprSyntax)
  case dictionaryExpr(DictionaryExprSyntax)
  case tupleExprElement(TupleExprElementSyntax)
  case arrayElement(ArrayElementSyntax)
  case dictionaryElement(DictionaryElementSyntax)
  case integerLiteralExpr(IntegerLiteralExprSyntax)
  case booleanLiteralExpr(BooleanLiteralExprSyntax)
  case ternaryExpr(TernaryExprSyntax)
  case memberAccessExpr(MemberAccessExprSyntax)
  case isExpr(IsExprSyntax)
  case asExpr(AsExprSyntax)
  case typeExpr(TypeExprSyntax)
  case closureCaptureItem(ClosureCaptureItemSyntax)
  case closureCaptureItemList(ClosureCaptureItemListSyntax)
  case closureCaptureSignature(ClosureCaptureSignatureSyntax)
  case closureParam(ClosureParamSyntax)
  case closureParamList(ClosureParamListSyntax)
  case closureSignature(ClosureSignatureSyntax)
  case closureExpr(ClosureExprSyntax)
  case unresolvedPatternExpr(UnresolvedPatternExprSyntax)
  case multipleTrailingClosureElement(MultipleTrailingClosureElementSyntax)
  case multipleTrailingClosureElementList(MultipleTrailingClosureElementListSyntax)
  case functionCallExpr(FunctionCallExprSyntax)
  case subscriptExpr(SubscriptExprSyntax)
  case optionalChainingExpr(OptionalChainingExprSyntax)
  case forcedValueExpr(ForcedValueExprSyntax)
  case postfixUnaryExpr(PostfixUnaryExprSyntax)
  case specializeExpr(SpecializeExprSyntax)
  case stringSegment(StringSegmentSyntax)
  case expressionSegment(ExpressionSegmentSyntax)
  case stringLiteralExpr(StringLiteralExprSyntax)
  case regexLiteralExpr(RegexLiteralExprSyntax)
  case keyPathExpr(KeyPathExprSyntax)
  case keyPathBaseExpr(KeyPathBaseExprSyntax)
  case objcNamePiece(ObjcNamePieceSyntax)
  case objcName(ObjcNameSyntax)
  case objcKeyPathExpr(ObjcKeyPathExprSyntax)
  case objcSelectorExpr(ObjcSelectorExprSyntax)
  case postfixIfConfigExpr(PostfixIfConfigExprSyntax)
  case editorPlaceholderExpr(EditorPlaceholderExprSyntax)
  case objectLiteralExpr(ObjectLiteralExprSyntax)
  case typeInitializerClause(TypeInitializerClauseSyntax)
  case typealiasDecl(TypealiasDeclSyntax)
  case associatedtypeDecl(AssociatedtypeDeclSyntax)
  case functionParameterList(FunctionParameterListSyntax)
  case parameterClause(ParameterClauseSyntax)
  case returnClause(ReturnClauseSyntax)
  case functionSignature(FunctionSignatureSyntax)
  case ifConfigClause(IfConfigClauseSyntax)
  case ifConfigClauseList(IfConfigClauseListSyntax)
  case ifConfigDecl(IfConfigDeclSyntax)
  case poundErrorDecl(PoundErrorDeclSyntax)
  case poundWarningDecl(PoundWarningDeclSyntax)
  case poundSourceLocation(PoundSourceLocationSyntax)
  case poundSourceLocationArgs(PoundSourceLocationArgsSyntax)
  case declModifierDetail(DeclModifierDetailSyntax)
  case declModifier(DeclModifierSyntax)
  case inheritedType(InheritedTypeSyntax)
  case inheritedTypeList(InheritedTypeListSyntax)
  case typeInheritanceClause(TypeInheritanceClauseSyntax)
  case classDecl(ClassDeclSyntax)
  case actorDecl(ActorDeclSyntax)
  case structDecl(StructDeclSyntax)
  case protocolDecl(ProtocolDeclSyntax)
  case extensionDecl(ExtensionDeclSyntax)
  case memberDeclBlock(MemberDeclBlockSyntax)
  case memberDeclList(MemberDeclListSyntax)
  case memberDeclListItem(MemberDeclListItemSyntax)
  case sourceFile(SourceFileSyntax)
  case initializerClause(InitializerClauseSyntax)
  case functionParameter(FunctionParameterSyntax)
  case modifierList(ModifierListSyntax)
  case functionDecl(FunctionDeclSyntax)
  case initializerDecl(InitializerDeclSyntax)
  case deinitializerDecl(DeinitializerDeclSyntax)
  case subscriptDecl(SubscriptDeclSyntax)
  case accessLevelModifier(AccessLevelModifierSyntax)
  case accessPathComponent(AccessPathComponentSyntax)
  case accessPath(AccessPathSyntax)
  case importDecl(ImportDeclSyntax)
  case accessorParameter(AccessorParameterSyntax)
  case accessorDecl(AccessorDeclSyntax)
  case accessorList(AccessorListSyntax)
  case accessorBlock(AccessorBlockSyntax)
  case patternBinding(PatternBindingSyntax)
  case patternBindingList(PatternBindingListSyntax)
  case variableDecl(VariableDeclSyntax)
  case enumCaseElement(EnumCaseElementSyntax)
  case enumCaseElementList(EnumCaseElementListSyntax)
  case enumCaseDecl(EnumCaseDeclSyntax)
  case enumDecl(EnumDeclSyntax)
  case operatorDecl(OperatorDeclSyntax)
  case identifierList(IdentifierListSyntax)
  case operatorPrecedenceAndTypes(OperatorPrecedenceAndTypesSyntax)
  case precedenceGroupDecl(PrecedenceGroupDeclSyntax)
  case precedenceGroupAttributeList(PrecedenceGroupAttributeListSyntax)
  case precedenceGroupRelation(PrecedenceGroupRelationSyntax)
  case precedenceGroupNameList(PrecedenceGroupNameListSyntax)
  case precedenceGroupNameElement(PrecedenceGroupNameElementSyntax)
  case precedenceGroupAssignment(PrecedenceGroupAssignmentSyntax)
  case precedenceGroupAssociativity(PrecedenceGroupAssociativitySyntax)
  case tokenList(TokenListSyntax)
  case nonEmptyTokenList(NonEmptyTokenListSyntax)
  case customAttribute(CustomAttributeSyntax)
  case attribute(AttributeSyntax)
  case attributeList(AttributeListSyntax)
  case specializeAttributeSpecList(SpecializeAttributeSpecListSyntax)
  case availabilityEntry(AvailabilityEntrySyntax)
  case labeledSpecializeEntry(LabeledSpecializeEntrySyntax)
  case targetFunctionEntry(TargetFunctionEntrySyntax)
  case namedAttributeStringArgument(NamedAttributeStringArgumentSyntax)
  case declName(DeclNameSyntax)
  case implementsAttributeArguments(ImplementsAttributeArgumentsSyntax)
  case objCSelectorPiece(ObjCSelectorPieceSyntax)
  case objCSelector(ObjCSelectorSyntax)
  case differentiableAttributeArguments(DifferentiableAttributeArgumentsSyntax)
  case differentiabilityParamsClause(DifferentiabilityParamsClauseSyntax)
  case differentiabilityParams(DifferentiabilityParamsSyntax)
  case differentiabilityParamList(DifferentiabilityParamListSyntax)
  case differentiabilityParam(DifferentiabilityParamSyntax)
  case derivativeRegistrationAttributeArguments(DerivativeRegistrationAttributeArgumentsSyntax)
  case qualifiedDeclName(QualifiedDeclNameSyntax)
  case functionDeclName(FunctionDeclNameSyntax)
  case backDeployAttributeSpecList(BackDeployAttributeSpecListSyntax)
  case backDeployVersionList(BackDeployVersionListSyntax)
  case backDeployVersionArgument(BackDeployVersionArgumentSyntax)
  case continueStmt(ContinueStmtSyntax)
  case whileStmt(WhileStmtSyntax)
  case deferStmt(DeferStmtSyntax)
  case expressionStmt(ExpressionStmtSyntax)
  case switchCaseList(SwitchCaseListSyntax)
  case repeatWhileStmt(RepeatWhileStmtSyntax)
  case guardStmt(GuardStmtSyntax)
  case whereClause(WhereClauseSyntax)
  case forInStmt(ForInStmtSyntax)
  case switchStmt(SwitchStmtSyntax)
  case catchClauseList(CatchClauseListSyntax)
  case doStmt(DoStmtSyntax)
  case returnStmt(ReturnStmtSyntax)
  case yieldStmt(YieldStmtSyntax)
  case yieldList(YieldListSyntax)
  case fallthroughStmt(FallthroughStmtSyntax)
  case breakStmt(BreakStmtSyntax)
  case caseItemList(CaseItemListSyntax)
  case catchItemList(CatchItemListSyntax)
  case conditionElement(ConditionElementSyntax)
  case availabilityCondition(AvailabilityConditionSyntax)
  case matchingPatternCondition(MatchingPatternConditionSyntax)
  case optionalBindingCondition(OptionalBindingConditionSyntax)
  case unavailabilityCondition(UnavailabilityConditionSyntax)
  case conditionElementList(ConditionElementListSyntax)
  case declarationStmt(DeclarationStmtSyntax)
  case throwStmt(ThrowStmtSyntax)
  case ifStmt(IfStmtSyntax)
  case elseIfContinuation(ElseIfContinuationSyntax)
  case elseBlock(ElseBlockSyntax)
  case switchCase(SwitchCaseSyntax)
  case switchDefaultLabel(SwitchDefaultLabelSyntax)
  case caseItem(CaseItemSyntax)
  case catchItem(CatchItemSyntax)
  case switchCaseLabel(SwitchCaseLabelSyntax)
  case catchClause(CatchClauseSyntax)
  case poundAssertStmt(PoundAssertStmtSyntax)
  case genericWhereClause(GenericWhereClauseSyntax)
  case genericRequirementList(GenericRequirementListSyntax)
  case genericRequirement(GenericRequirementSyntax)
  case sameTypeRequirement(SameTypeRequirementSyntax)
  case genericParameterList(GenericParameterListSyntax)
  case genericParameter(GenericParameterSyntax)
  case primaryAssociatedTypeList(PrimaryAssociatedTypeListSyntax)
  case primaryAssociatedType(PrimaryAssociatedTypeSyntax)
  case genericParameterClause(GenericParameterClauseSyntax)
  case conformanceRequirement(ConformanceRequirementSyntax)
  case primaryAssociatedTypeClause(PrimaryAssociatedTypeClauseSyntax)
  case simpleTypeIdentifier(SimpleTypeIdentifierSyntax)
  case memberTypeIdentifier(MemberTypeIdentifierSyntax)
  case classRestrictionType(ClassRestrictionTypeSyntax)
  case arrayType(ArrayTypeSyntax)
  case dictionaryType(DictionaryTypeSyntax)
  case metatypeType(MetatypeTypeSyntax)
  case optionalType(OptionalTypeSyntax)
  case constrainedSugarType(ConstrainedSugarTypeSyntax)
  case implicitlyUnwrappedOptionalType(ImplicitlyUnwrappedOptionalTypeSyntax)
  case compositionTypeElement(CompositionTypeElementSyntax)
  case compositionTypeElementList(CompositionTypeElementListSyntax)
  case compositionType(CompositionTypeSyntax)
  case tupleTypeElement(TupleTypeElementSyntax)
  case tupleTypeElementList(TupleTypeElementListSyntax)
  case tupleType(TupleTypeSyntax)
  case functionType(FunctionTypeSyntax)
  case attributedType(AttributedTypeSyntax)
  case genericArgumentList(GenericArgumentListSyntax)
  case genericArgument(GenericArgumentSyntax)
  case genericArgumentClause(GenericArgumentClauseSyntax)
  case typeAnnotation(TypeAnnotationSyntax)
  case enumCasePattern(EnumCasePatternSyntax)
  case isTypePattern(IsTypePatternSyntax)
  case optionalPattern(OptionalPatternSyntax)
  case identifierPattern(IdentifierPatternSyntax)
  case asTypePattern(AsTypePatternSyntax)
  case tuplePattern(TuplePatternSyntax)
  case wildcardPattern(WildcardPatternSyntax)
  case tuplePatternElement(TuplePatternElementSyntax)
  case expressionPattern(ExpressionPatternSyntax)
  case tuplePatternElementList(TuplePatternElementListSyntax)
  case valueBindingPattern(ValueBindingPatternSyntax)
  case availabilitySpecList(AvailabilitySpecListSyntax)
  case availabilityArgument(AvailabilityArgumentSyntax)
  case availabilityLabeledArgument(AvailabilityLabeledArgumentSyntax)
  case availabilityVersionRestriction(AvailabilityVersionRestrictionSyntax)
  case versionTuple(VersionTupleSyntax)
}

public extension Syntax {
  /// Get an enum that can be used to exhaustively switch over all syntax nodes.
  func `as`(_: SyntaxEnum.Type) -> SyntaxEnum {
    switch raw.syntaxKind {
    case .token:
      return .token(TokenSyntax(self)!)
    case .unknown:
      return .unknown(UnknownSyntax(self)!)
    case .decl: return .decl(.init(data: data))
    case .expr: return .expr(.init(data: data))
    case .stmt: return .stmt(.init(data: data))
    case .type: return .type(.init(data: data))
    case .pattern: return .pattern(.init(data: data))
    case .unknownDecl: return .unknownDecl(.init(data: data))
    case .unknownExpr: return .unknownExpr(.init(data: data))
    case .unknownStmt: return .unknownStmt(.init(data: data))
    case .unknownType: return .unknownType(.init(data: data))
    case .unknownPattern: return .unknownPattern(.init(data: data))
    case .codeBlockItem: return .codeBlockItem(.init(data: data))
    case .codeBlockItemList: return .codeBlockItemList(.init(data: data))
    case .codeBlock: return .codeBlock(.init(data: data))
    case .inOutExpr: return .inOutExpr(.init(data: data))
    case .poundColumnExpr: return .poundColumnExpr(.init(data: data))
    case .tupleExprElementList: return .tupleExprElementList(.init(data: data))
    case .arrayElementList: return .arrayElementList(.init(data: data))
    case .dictionaryElementList: return .dictionaryElementList(.init(data: data))
    case .stringLiteralSegments: return .stringLiteralSegments(.init(data: data))
    case .tryExpr: return .tryExpr(.init(data: data))
    case .awaitExpr: return .awaitExpr(.init(data: data))
    case .declNameArgument: return .declNameArgument(.init(data: data))
    case .declNameArgumentList: return .declNameArgumentList(.init(data: data))
    case .declNameArguments: return .declNameArguments(.init(data: data))
    case .identifierExpr: return .identifierExpr(.init(data: data))
    case .superRefExpr: return .superRefExpr(.init(data: data))
    case .nilLiteralExpr: return .nilLiteralExpr(.init(data: data))
    case .discardAssignmentExpr: return .discardAssignmentExpr(.init(data: data))
    case .assignmentExpr: return .assignmentExpr(.init(data: data))
    case .sequenceExpr: return .sequenceExpr(.init(data: data))
    case .exprList: return .exprList(.init(data: data))
    case .poundLineExpr: return .poundLineExpr(.init(data: data))
    case .poundFileExpr: return .poundFileExpr(.init(data: data))
    case .poundFileIDExpr: return .poundFileIDExpr(.init(data: data))
    case .poundFilePathExpr: return .poundFilePathExpr(.init(data: data))
    case .poundFunctionExpr: return .poundFunctionExpr(.init(data: data))
    case .poundDsohandleExpr: return .poundDsohandleExpr(.init(data: data))
    case .symbolicReferenceExpr: return .symbolicReferenceExpr(.init(data: data))
    case .prefixOperatorExpr: return .prefixOperatorExpr(.init(data: data))
    case .binaryOperatorExpr: return .binaryOperatorExpr(.init(data: data))
    case .arrowExpr: return .arrowExpr(.init(data: data))
    case .floatLiteralExpr: return .floatLiteralExpr(.init(data: data))
    case .tupleExpr: return .tupleExpr(.init(data: data))
    case .arrayExpr: return .arrayExpr(.init(data: data))
    case .dictionaryExpr: return .dictionaryExpr(.init(data: data))
    case .tupleExprElement: return .tupleExprElement(.init(data: data))
    case .arrayElement: return .arrayElement(.init(data: data))
    case .dictionaryElement: return .dictionaryElement(.init(data: data))
    case .integerLiteralExpr: return .integerLiteralExpr(.init(data: data))
    case .booleanLiteralExpr: return .booleanLiteralExpr(.init(data: data))
    case .ternaryExpr: return .ternaryExpr(.init(data: data))
    case .memberAccessExpr: return .memberAccessExpr(.init(data: data))
    case .isExpr: return .isExpr(.init(data: data))
    case .asExpr: return .asExpr(.init(data: data))
    case .typeExpr: return .typeExpr(.init(data: data))
    case .closureCaptureItem: return .closureCaptureItem(.init(data: data))
    case .closureCaptureItemList: return .closureCaptureItemList(.init(data: data))
    case .closureCaptureSignature: return .closureCaptureSignature(.init(data: data))
    case .closureParam: return .closureParam(.init(data: data))
    case .closureParamList: return .closureParamList(.init(data: data))
    case .closureSignature: return .closureSignature(.init(data: data))
    case .closureExpr: return .closureExpr(.init(data: data))
    case .unresolvedPatternExpr: return .unresolvedPatternExpr(.init(data: data))
    case .multipleTrailingClosureElement: return .multipleTrailingClosureElement(.init(data: data))
    case .multipleTrailingClosureElementList: return .multipleTrailingClosureElementList(.init(data: data))
    case .functionCallExpr: return .functionCallExpr(.init(data: data))
    case .subscriptExpr: return .subscriptExpr(.init(data: data))
    case .optionalChainingExpr: return .optionalChainingExpr(.init(data: data))
    case .forcedValueExpr: return .forcedValueExpr(.init(data: data))
    case .postfixUnaryExpr: return .postfixUnaryExpr(.init(data: data))
    case .specializeExpr: return .specializeExpr(.init(data: data))
    case .stringSegment: return .stringSegment(.init(data: data))
    case .expressionSegment: return .expressionSegment(.init(data: data))
    case .stringLiteralExpr: return .stringLiteralExpr(.init(data: data))
    case .regexLiteralExpr: return .regexLiteralExpr(.init(data: data))
    case .keyPathExpr: return .keyPathExpr(.init(data: data))
    case .keyPathBaseExpr: return .keyPathBaseExpr(.init(data: data))
    case .objcNamePiece: return .objcNamePiece(.init(data: data))
    case .objcName: return .objcName(.init(data: data))
    case .objcKeyPathExpr: return .objcKeyPathExpr(.init(data: data))
    case .objcSelectorExpr: return .objcSelectorExpr(.init(data: data))
    case .postfixIfConfigExpr: return .postfixIfConfigExpr(.init(data: data))
    case .editorPlaceholderExpr: return .editorPlaceholderExpr(.init(data: data))
    case .objectLiteralExpr: return .objectLiteralExpr(.init(data: data))
    case .typeInitializerClause: return .typeInitializerClause(.init(data: data))
    case .typealiasDecl: return .typealiasDecl(.init(data: data))
    case .associatedtypeDecl: return .associatedtypeDecl(.init(data: data))
    case .functionParameterList: return .functionParameterList(.init(data: data))
    case .parameterClause: return .parameterClause(.init(data: data))
    case .returnClause: return .returnClause(.init(data: data))
    case .functionSignature: return .functionSignature(.init(data: data))
    case .ifConfigClause: return .ifConfigClause(.init(data: data))
    case .ifConfigClauseList: return .ifConfigClauseList(.init(data: data))
    case .ifConfigDecl: return .ifConfigDecl(.init(data: data))
    case .poundErrorDecl: return .poundErrorDecl(.init(data: data))
    case .poundWarningDecl: return .poundWarningDecl(.init(data: data))
    case .poundSourceLocation: return .poundSourceLocation(.init(data: data))
    case .poundSourceLocationArgs: return .poundSourceLocationArgs(.init(data: data))
    case .declModifierDetail: return .declModifierDetail(.init(data: data))
    case .declModifier: return .declModifier(.init(data: data))
    case .inheritedType: return .inheritedType(.init(data: data))
    case .inheritedTypeList: return .inheritedTypeList(.init(data: data))
    case .typeInheritanceClause: return .typeInheritanceClause(.init(data: data))
    case .classDecl: return .classDecl(.init(data: data))
    case .actorDecl: return .actorDecl(.init(data: data))
    case .structDecl: return .structDecl(.init(data: data))
    case .protocolDecl: return .protocolDecl(.init(data: data))
    case .extensionDecl: return .extensionDecl(.init(data: data))
    case .memberDeclBlock: return .memberDeclBlock(.init(data: data))
    case .memberDeclList: return .memberDeclList(.init(data: data))
    case .memberDeclListItem: return .memberDeclListItem(.init(data: data))
    case .sourceFile: return .sourceFile(.init(data: data))
    case .initializerClause: return .initializerClause(.init(data: data))
    case .functionParameter: return .functionParameter(.init(data: data))
    case .modifierList: return .modifierList(.init(data: data))
    case .functionDecl: return .functionDecl(.init(data: data))
    case .initializerDecl: return .initializerDecl(.init(data: data))
    case .deinitializerDecl: return .deinitializerDecl(.init(data: data))
    case .subscriptDecl: return .subscriptDecl(.init(data: data))
    case .accessLevelModifier: return .accessLevelModifier(.init(data: data))
    case .accessPathComponent: return .accessPathComponent(.init(data: data))
    case .accessPath: return .accessPath(.init(data: data))
    case .importDecl: return .importDecl(.init(data: data))
    case .accessorParameter: return .accessorParameter(.init(data: data))
    case .accessorDecl: return .accessorDecl(.init(data: data))
    case .accessorList: return .accessorList(.init(data: data))
    case .accessorBlock: return .accessorBlock(.init(data: data))
    case .patternBinding: return .patternBinding(.init(data: data))
    case .patternBindingList: return .patternBindingList(.init(data: data))
    case .variableDecl: return .variableDecl(.init(data: data))
    case .enumCaseElement: return .enumCaseElement(.init(data: data))
    case .enumCaseElementList: return .enumCaseElementList(.init(data: data))
    case .enumCaseDecl: return .enumCaseDecl(.init(data: data))
    case .enumDecl: return .enumDecl(.init(data: data))
    case .operatorDecl: return .operatorDecl(.init(data: data))
    case .identifierList: return .identifierList(.init(data: data))
    case .operatorPrecedenceAndTypes: return .operatorPrecedenceAndTypes(.init(data: data))
    case .precedenceGroupDecl: return .precedenceGroupDecl(.init(data: data))
    case .precedenceGroupAttributeList: return .precedenceGroupAttributeList(.init(data: data))
    case .precedenceGroupRelation: return .precedenceGroupRelation(.init(data: data))
    case .precedenceGroupNameList: return .precedenceGroupNameList(.init(data: data))
    case .precedenceGroupNameElement: return .precedenceGroupNameElement(.init(data: data))
    case .precedenceGroupAssignment: return .precedenceGroupAssignment(.init(data: data))
    case .precedenceGroupAssociativity: return .precedenceGroupAssociativity(.init(data: data))
    case .tokenList: return .tokenList(.init(data: data))
    case .nonEmptyTokenList: return .nonEmptyTokenList(.init(data: data))
    case .customAttribute: return .customAttribute(.init(data: data))
    case .attribute: return .attribute(.init(data: data))
    case .attributeList: return .attributeList(.init(data: data))
    case .specializeAttributeSpecList: return .specializeAttributeSpecList(.init(data: data))
    case .availabilityEntry: return .availabilityEntry(.init(data: data))
    case .labeledSpecializeEntry: return .labeledSpecializeEntry(.init(data: data))
    case .targetFunctionEntry: return .targetFunctionEntry(.init(data: data))
    case .namedAttributeStringArgument: return .namedAttributeStringArgument(.init(data: data))
    case .declName: return .declName(.init(data: data))
    case .implementsAttributeArguments: return .implementsAttributeArguments(.init(data: data))
    case .objCSelectorPiece: return .objCSelectorPiece(.init(data: data))
    case .objCSelector: return .objCSelector(.init(data: data))
    case .differentiableAttributeArguments: return .differentiableAttributeArguments(.init(data: data))
    case .differentiabilityParamsClause: return .differentiabilityParamsClause(.init(data: data))
    case .differentiabilityParams: return .differentiabilityParams(.init(data: data))
    case .differentiabilityParamList: return .differentiabilityParamList(.init(data: data))
    case .differentiabilityParam: return .differentiabilityParam(.init(data: data))
    case .derivativeRegistrationAttributeArguments: return .derivativeRegistrationAttributeArguments(.init(data: data))
    case .qualifiedDeclName: return .qualifiedDeclName(.init(data: data))
    case .functionDeclName: return .functionDeclName(.init(data: data))
    case .backDeployAttributeSpecList: return .backDeployAttributeSpecList(.init(data: data))
    case .backDeployVersionList: return .backDeployVersionList(.init(data: data))
    case .backDeployVersionArgument: return .backDeployVersionArgument(.init(data: data))
    case .continueStmt: return .continueStmt(.init(data: data))
    case .whileStmt: return .whileStmt(.init(data: data))
    case .deferStmt: return .deferStmt(.init(data: data))
    case .expressionStmt: return .expressionStmt(.init(data: data))
    case .switchCaseList: return .switchCaseList(.init(data: data))
    case .repeatWhileStmt: return .repeatWhileStmt(.init(data: data))
    case .guardStmt: return .guardStmt(.init(data: data))
    case .whereClause: return .whereClause(.init(data: data))
    case .forInStmt: return .forInStmt(.init(data: data))
    case .switchStmt: return .switchStmt(.init(data: data))
    case .catchClauseList: return .catchClauseList(.init(data: data))
    case .doStmt: return .doStmt(.init(data: data))
    case .returnStmt: return .returnStmt(.init(data: data))
    case .yieldStmt: return .yieldStmt(.init(data: data))
    case .yieldList: return .yieldList(.init(data: data))
    case .fallthroughStmt: return .fallthroughStmt(.init(data: data))
    case .breakStmt: return .breakStmt(.init(data: data))
    case .caseItemList: return .caseItemList(.init(data: data))
    case .catchItemList: return .catchItemList(.init(data: data))
    case .conditionElement: return .conditionElement(.init(data: data))
    case .availabilityCondition: return .availabilityCondition(.init(data: data))
    case .matchingPatternCondition: return .matchingPatternCondition(.init(data: data))
    case .optionalBindingCondition: return .optionalBindingCondition(.init(data: data))
    case .unavailabilityCondition: return .unavailabilityCondition(.init(data: data))
    case .conditionElementList: return .conditionElementList(.init(data: data))
    case .declarationStmt: return .declarationStmt(.init(data: data))
    case .throwStmt: return .throwStmt(.init(data: data))
    case .ifStmt: return .ifStmt(.init(data: data))
    case .elseIfContinuation: return .elseIfContinuation(.init(data: data))
    case .elseBlock: return .elseBlock(.init(data: data))
    case .switchCase: return .switchCase(.init(data: data))
    case .switchDefaultLabel: return .switchDefaultLabel(.init(data: data))
    case .caseItem: return .caseItem(.init(data: data))
    case .catchItem: return .catchItem(.init(data: data))
    case .switchCaseLabel: return .switchCaseLabel(.init(data: data))
    case .catchClause: return .catchClause(.init(data: data))
    case .poundAssertStmt: return .poundAssertStmt(.init(data: data))
    case .genericWhereClause: return .genericWhereClause(.init(data: data))
    case .genericRequirementList: return .genericRequirementList(.init(data: data))
    case .genericRequirement: return .genericRequirement(.init(data: data))
    case .sameTypeRequirement: return .sameTypeRequirement(.init(data: data))
    case .genericParameterList: return .genericParameterList(.init(data: data))
    case .genericParameter: return .genericParameter(.init(data: data))
    case .primaryAssociatedTypeList: return .primaryAssociatedTypeList(.init(data: data))
    case .primaryAssociatedType: return .primaryAssociatedType(.init(data: data))
    case .genericParameterClause: return .genericParameterClause(.init(data: data))
    case .conformanceRequirement: return .conformanceRequirement(.init(data: data))
    case .primaryAssociatedTypeClause: return .primaryAssociatedTypeClause(.init(data: data))
    case .simpleTypeIdentifier: return .simpleTypeIdentifier(.init(data: data))
    case .memberTypeIdentifier: return .memberTypeIdentifier(.init(data: data))
    case .classRestrictionType: return .classRestrictionType(.init(data: data))
    case .arrayType: return .arrayType(.init(data: data))
    case .dictionaryType: return .dictionaryType(.init(data: data))
    case .metatypeType: return .metatypeType(.init(data: data))
    case .optionalType: return .optionalType(.init(data: data))
    case .constrainedSugarType: return .constrainedSugarType(.init(data: data))
    case .implicitlyUnwrappedOptionalType: return .implicitlyUnwrappedOptionalType(.init(data: data))
    case .compositionTypeElement: return .compositionTypeElement(.init(data: data))
    case .compositionTypeElementList: return .compositionTypeElementList(.init(data: data))
    case .compositionType: return .compositionType(.init(data: data))
    case .tupleTypeElement: return .tupleTypeElement(.init(data: data))
    case .tupleTypeElementList: return .tupleTypeElementList(.init(data: data))
    case .tupleType: return .tupleType(.init(data: data))
    case .functionType: return .functionType(.init(data: data))
    case .attributedType: return .attributedType(.init(data: data))
    case .genericArgumentList: return .genericArgumentList(.init(data: data))
    case .genericArgument: return .genericArgument(.init(data: data))
    case .genericArgumentClause: return .genericArgumentClause(.init(data: data))
    case .typeAnnotation: return .typeAnnotation(.init(data: data))
    case .enumCasePattern: return .enumCasePattern(.init(data: data))
    case .isTypePattern: return .isTypePattern(.init(data: data))
    case .optionalPattern: return .optionalPattern(.init(data: data))
    case .identifierPattern: return .identifierPattern(.init(data: data))
    case .asTypePattern: return .asTypePattern(.init(data: data))
    case .tuplePattern: return .tuplePattern(.init(data: data))
    case .wildcardPattern: return .wildcardPattern(.init(data: data))
    case .tuplePatternElement: return .tuplePatternElement(.init(data: data))
    case .expressionPattern: return .expressionPattern(.init(data: data))
    case .tuplePatternElementList: return .tuplePatternElementList(.init(data: data))
    case .valueBindingPattern: return .valueBindingPattern(.init(data: data))
    case .availabilitySpecList: return .availabilitySpecList(.init(data: data))
    case .availabilityArgument: return .availabilityArgument(.init(data: data))
    case .availabilityLabeledArgument: return .availabilityLabeledArgument(.init(data: data))
    case .availabilityVersionRestriction: return .availabilityVersionRestriction(.init(data: data))
    case .versionTuple: return .versionTuple(.init(data: data))
    }
  }
}
