//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2022 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import SwiftSyntax
import SwiftSyntaxBuilder

let copyrightHeader = """
    //// Automatically Generated by SwiftSyntaxBuilderGeneration
    //// Do Not Edit Directly!
    //===----------------------------------------------------------------------===//
    //
    // This source file is part of the Swift.org open source project
    //
    // Copyright (c) 2014 - 2022 Apple Inc. and the Swift project authors
    // Licensed under Apache License v2.0 with Runtime Library Exception
    //
    // See https://swift.org/LICENSE.txt for license information
    // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
    //
    //===----------------------------------------------------------------------===//


    """

func createSpacingCall() -> MemberAccessExpr {
  MemberAccessExpr(name: "space")
}

func createWithLeadingTriviaCall() -> FunctionCallExpr {
  FunctionCallExpr(MemberAccessExpr(name: "withLeadingTrivia")) {
    TupleExprElement(expression: createSpacingCall())
  }
}

func createWithTrailingTriviaCall() -> FunctionCallExpr {
  FunctionCallExpr(MemberAccessExpr(name: "withTrailingTrivia")) {
    TupleExprElement(expression: createSpacingCall())
  }
}

func createTokenSyntaxPatternBinding(_ pattern: ExpressibleAsPatternBuildable, accessor: ExpressibleAsSyntaxBuildable) -> PatternBinding {
  PatternBinding(pattern: pattern,
                 typeAnnotation: "TokenSyntax",
                 initializer: nil,
                 accessor: accessor)
}

func createTypeInheritanceClause(conformances: [String]) -> TypeInheritanceClause? {
  conformances.isEmpty ? nil : TypeInheritanceClause {
    for conformance in conformances {
      InheritedType(typeName: conformance)
    }
  }
}

/// Create a parameter clause of the form `format: .comma, leadingTrivia: Trivia = nil`
/// where the presence of ` = nil` is controlled by `withDefaultTrivia`.
func createFormatLeadingTriviaParameters(withDefaultTrivia: Bool = false) -> ParameterClause {
  ParameterClause {
    FunctionParameter(
      firstName: .identifier("format"),
      colon: .colon,
      type: "Format"
    )
    FunctionParameter(
      firstName: .identifier("leadingTrivia"),
      colon: .colon,
      type: OptionalType(wrappedType: "Trivia"),
      defaultArgument: withDefaultTrivia ? InitializerClause(value: NilLiteralExpr()) : nil
    )
  }
}
