name: Bug Report
description: Something isn't working as expected
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A short description of the incorrect behavior.
        If you think this issue has been recently introduced and did not occur in an
        earlier version, please note that. If possible, include the last version that
        the behavior was correct in addition to your current version.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Replace this paragraph with an explanation of how to reproduce the incorrect behavior.
