BUILDER_INITIALIZABLE_TYPES = {
    'CodeBlock': 'CodeBlockItemList',
    'MemberDeclBlock': 'MemberDeclList',
    'CodeBlockItemList': None,
    'MemberDeclList': None,
    'PatternBindingList': None,
    'SwitchCaseList': None,
    'ArrayElementList': None,
    'TupleExprElementList': None,
    'EnumCaseElementList': None,
    'FunctionParameterList': None,
    'GenericParameterList': None,
    'GenericRequirementList': None,
    'InheritedTypeList': None,
    'ClosureCaptureItemList': None,
    'CaseItemList': None,
    'GenericArgumentList': None,
    'TuplePatternElementList': None,
    'ExprList': None,
}
