//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2022 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

import SwiftSyntax
import SwiftSyntaxBuilder

let copyrightHeader = """
    //// Automatically Generated by SwiftSyntaxBuilderGeneration
    //// Do Not Edit Directly!
    //===----------------------------------------------------------------------===//
    //
    // This source file is part of the Swift.org open source project
    //
    // Copyright (c) 2014 - 2022 Apple Inc. and the Swift project authors
    // Licensed under Apache License v2.0 with Runtime Library Exception
    //
    // See https://swift.org/LICENSE.txt for license information
    // See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
    //
    //===----------------------------------------------------------------------===//


    """

func createSpacingCall() -> MemberAccessExpr {
  MemberAccessExpr(name: "space")
}

func createWithLeadingTriviaCall() -> FunctionCallExpr {
  FunctionCallExpr(MemberAccessExpr(name: "withLeadingTrivia")) {
    TupleExprElement(expression: createSpacingCall())
  }
}

func createWithTrailingTriviaCall() -> FunctionCallExpr {
  FunctionCallExpr(MemberAccessExpr(name: "withTrailingTrivia")) {
    TupleExprElement(expression: createSpacingCall())
  }
}

func createTokenSyntaxPatternBinding(_ pattern: ExpressibleAsPatternBuildable, accessor: ExpressibleAsSyntaxBuildable) -> PatternBinding {
  PatternBinding(pattern: pattern,
                 typeAnnotation: "TokenSyntax",
                 initializer: nil,
                 accessor: accessor)
}
